books/urls.py
from django.urls import path
from books.views import BookListView, BookDetailView

app_name = 'books'
urlpatterns = [
    path('', BookListView.as_view(), name='list'),
    path('<int:book_id>/', BookDetailView.as_view(), name='detail'),
]

greads/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from .views import landing_page

urlpatterns = [
    path('', landing_page, name = 'landing_page'),
    path('users/', include('users.urls'), name='users'),
    path('books/', include('books.urls'), name='books'),
    path('admin/', admin.site.urls),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.views import RegisterView, LoginView, ProfileView, LogoutView, ProfileUpdateView

app_name = 'users'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/edit/', ProfileUpdateView.as_view(), name='profile-edit'),
]

books/models.py
from users.models import CustomUser
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models

# Create your models here.

class Book(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    isbn = models.CharField(max_length=17)
    cover_picture = models.ImageField(upload_to='cover_pictures', default='cover_pictures/default.jpg')


    def __str__(self):
        return self.title


class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    bio = models.TextField()

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

class BookAuthor(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.author} - {self.book}'


class BookReview(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    comment = models.TextField()
    stars_given = models.IntegerField(validators=[MinValueValidator(1),MaxValueValidator(5)])

    def __str__(self):
        return f'{self.stars_given} for {self.book} by {self.user}'

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models



class CustomUser(AbstractUser):
    profile_picture = models.ImageField(default='default_profile_pictures.png', upload_to='profile_pictures')

users/forms.py
from django import forms
from users.models import CustomUser


# class UserCreateForm(forms.Form):
#     username = forms.CharField(max_length=150)
#     email = forms.EmailField()
#     first_name = forms.CharField(max_length=150)
#     last_name = forms.CharField(max_length=150)
#     password = forms.CharField(max_length=128)
#
#     def save(self):
#         username = self.cleaned_data['username']
#         firstname = self.cleaned_data['first_name']
#         lastname = self.cleaned_data['last_name']
#         email = self.cleaned_data['email']
#         password = self.cleaned_data['password']
#
#         user = CustomUser.objects.create(
#             username=username,
#             first_name=firstname,
#             last_name=lastname,
#             email=email,
#             is_staff=True,
#             is_superuser=True
#         )
#         user.set_password(password)
#
#         user.save()

class UserCreateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('username','email','first_name','last_name', 'password')

    def save(self, commit=True):
        user = super().save(commit)
        user.set_password(self.cleaned_data['password'])
        user.save()

        return user

class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'first_name', 'last_name', 'email', 'profile_picture')




# class UserLoginForm(forms.Form):
#     username = forms.CharField(max_length=150)
#     password = forms.CharField(max_length=128)
#
#     # def clean(self):
    #     username = self.cleaned_data.get('username')
    #     password = self.cleaned_data.get('password')

books/views.py
from django.shortcuts import render
from django.views.generic import View

from books.models import Book

class BookListView(View):
    def get(self, request):
        books = Book.objects.all()
        context = {'books': books}
        return render(request, 'books/list.html', context)

class BookDetailView(View):
    def get(self, request, book_id):
        book = Book.objects.get(pk=book_id)

        context = {'book': book}
        return render(request, 'books/detail.html', context)

greads/views.py
from django.http import HttpResponse
from django.shortcuts import render


def landing_page(request):
    return render(request, 'landing_page.html')

users/views.py
from django.contrib import messages
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from users.models import CustomUser
from django.shortcuts import render, redirect
from django.views import View
from users.forms import UserCreateForm, UserUpdateForm


class RegisterView(View):
    def get(self, request):
        create_user = UserCreateForm()

        context = {
            'form':create_user
        }
        return render(request=request, template_name='users/register.html', context=context)

    def post(self, request):
        create_form = UserCreateForm(data=request.POST)

        if create_form.is_valid():
            create_form.save()
            return redirect('users:login')
        else:
            context = {
                'form': create_form
            }
            return render(request=request, template_name='users/register.html', context=context)

# class LoginView(View):
#     def get(self, request):
#         login_user = UserLoginForm()
#         context = {
#             'form': login_user
#         }
#         return render(request=request, template_name='users/login.html', context = context)
#
#     def post(self, request):
#         # login_form = UserLoginForm(data=request.POST)
#
#         login_form = AuthenticationForm(data=request.POST)
#
#         if login_form.is_valid():
#             # log in the user
#             print('salom dunyo')
#             return redirect('users:register')
#         else:
#             print('nima gap ozi')
#             return render(request, 'users/login.html',{'login_form': login_form})
#
#




class LoginView(View):
    def get(self, request):
        # login_form = UserLoginForm()
        login_form = AuthenticationForm()

        return render(request=request, template_name='users/login.html',context= {'form' : login_form})

    def post(self, request):
        # print(request.POST['username'], request.POST['password'])

        # login_form = UserLoginForm(data=request.POST)

        login_form = AuthenticationForm(data=request.POST)
        if login_form.is_valid():
            user = login_form.get_user()
            login(request, user)
            messages.success(request, 'You are now logged in')

            return redirect('books:list')
        else:
            return render(request=request, template_name='users/login.html',context= {'form' : login_form})

# class ProfileView(View):
#     def get(self, request):
#         user = request.user
#         if not user.is_authenticated:
#             return redirect('users:login')
#
#         return render(request, 'users/profile.html', {'user': request.user})


class ProfileView(LoginRequiredMixin,View):
    def get(self, request):
        return render(request, 'users/profile.html', {'user': request.user})



class LogoutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        messages.info(request, 'You have been logged out.')
        return redirect('landing_page')

class ProfileUpdateView(LoginRequiredMixin,View):
    def get(self, request):
        form = UserUpdateForm(instance=request.user)

        return render(request, 'users/profile_edit.html', {'form': form})

    def post(self, request):
        form = UserUpdateForm(
            instance = request.user,
            data = request.POST,
            files = request.FILES
        )

        if form.is_valid():
            form.save()
            messages.success(request, 'You have been updated successfully.')
            return redirect('users:profile')

        return render(request, 'users/profile_edit.html', {'form': form})

books/templates/books/detail.html
{% extends 'base.html' %}
{% block title %} Book detail page {% endblock %}


{% block content %}
<div class="row">
    <div class="col-2 ">
        <img class="cover-pic" src="{{ book.cover_picture.url }}" alt="">
    </div>
    <div class="col-6 ms-3">
        <h3>{{ book.title }}</h3>
        <p>{{ book.description }}</p>
    </div>

</div>

{% endblock %}

books/templates/books/list.html
{% extends 'base.html' %}
{% block title %} Book list page {% endblock %}


{% block content %}
    <h3>Books</h3>

    {% if books %}
        {% for book in books %}
            <div class="row mb-4">
                <div class="col-2">
                    <img class="cover-pic" src="{{ book.cover_picture.url }}" alt="">
                </div>
                <div class="col-6 ms-4">
                    <h4><a href="{% url 'books:detail' book.id %}">{{ book.title }}</a></h4>
                    <p>{{ book.description }}</p>
                </div>
            </div>       
        {% endfor %}

    {% else %}
        No books found.
    {% endif %}
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

{# https://getbootstrap.com/ #}
    <meta charset="UTF-8">
    <title>{% block title %} Goodreads Page {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">

</head>
<body class="mx-5">
<nav class="navbar navbar-expand-lg mb-4 bg-" style="background-color: #e3f2fd;" >
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'landing_page' %}">Goodreads clone</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'books:list' %}">Books</a>
        </li>

      </ul>
        <div class="me-5 " >
            {% if request.user.is_authenticated %}
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                          {{ request.user.username }}
                      </a>
                      <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'users:profile' %}">Profile</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a></li>
                      </ul>
                    </li>
                </ul>
            {% else %}

                <a href="{% url 'users:login' %}" class="btn btn-outline-primary">Login</a>
            {% endif %}

        </div>


    </div>
  </div>
</nav>


<div class="container ">
    {% if messages %}
        <div class="mt-3">
            {% for message in messages %}

                <div class="alert alert-{{ message.tags }}" role="alert">
                    {{ message }}
                </div>
            {% endfor %}
        </div>

    {% endif %}
    {% block content %} {% endblock %}
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

templates/landing_page.html
{% extends 'base.html' %}

{% block content %}
    <h1>Landing page</h1>
    <p>
        Goodreads is an American social cataloging website and a subsidiary of Amazon[1] that allows individuals to search its database of books, annotations, quotes, and reviews. Users can sign up and register books to generate library catalogs and reading lists. They can also create their own groups of book suggestions, surveys, polls, blogs, and discussions. The website's offices are located in San Francisco.[2]
        Goodreads was founded in December 2006 and launched in January 2007 by Otis Chandler and Elizabeth Khuri Chandler.[3][4] In December 2007, the site had 650,000 members[5] and 10,000,000 books had been added.[6] By July 2012, the site reported 10 million members, 20 million monthly visits, and thirty employees.[7] On March 28, 2013, Amazon announced its acquisition of Goodreads,[8] and by July 23, 2013, Goodreads announced their user base had grown to 20 million members.
    </p>
{% endblock %}

users/templates/users/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Login page {% endblock %}


{% block content %}

    <h3>Login page</h3>
    <div class="row">
        <div class="col-4">
            <form action="" method="post">
                {% csrf_token %}
                {{ form | crispy }}
                <button type="submit" class="btn btn-primary">Log in</button>
                <span class="ms-4">
                    No account? <a href="{% url 'users:register' %}">get register now</a>
                </span>
            </form>
        </div>
    </div>

{% endblock %}

users/templates/users/profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Profile page {% endblock %}


{% block content %}

    <div class="container mt-4 mb-4 p-3 d-flex justify-content-center">
        <div class="card p-4">
            <div class=" image d-flex flex-column justify-content-center align-items-center">
                <button class="btn btn-secondary">

                    <img class="profile-pic" src="{{ user.profile_picture.url }}" alt="">
                </button>
                <span class="name mt-3">{{ user.first_name }} {{ user.last_name }}</span>
                <span class="idd">@{{ user.username }}</span>
                <span class="idd">{{ user.email }}</span>

                <div class=" d-flex mt-2">
                    <a class="btn btn-dark" href="{% url 'users:profile-edit' %}">Edit profile</a>
                </div>

                <div class="gap-3 mt-3 icons d-flex flex-row justify-content-center align-items-center"><span><i
                        class="fa fa-twitter"></i></span> <span><i class="fa fa-facebook-f"></i></span> <span><i
                        class="fa fa-instagram"></i></span> <span><i class="fa fa-linkedin"></i></span></div>
                <div class=" px-2 rounded mt-4 date "><span class="join">Joined: {{ user.date_joined|date:"M Y " }}</span></div>
            </div>
        </div>
    </div>

{% endblock %}

users/templates/users/profile_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Edit Profile {% endblock %}

{% block content %}

    <h3>Edit Profile Page</h3>
    <div class="row">
        <div class="col-4">
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form | crispy }}
                <button class="btn btn-primary" type="submit">save changes</button>
            </form>
        </div>
    </div>
{% endblock %}

users/templates/users/register.html
{% extends 'base.html' %}
{% block title %} Register page {% endblock %}


{% block content %}
{% load crispy_forms_tags %}

<h3>Register page</h3>
<div class="row">
    <div class="col-4">
        <form method="post" action="{% url 'users:register' %}">{% csrf_token %}
            {{ form | crispy }}
            <button type="submit" class="btn btn-primary"> Yuborish </button>
        </form>
    </div>
</div>


{% endblock %}